import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spark Donation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://internship.thesparksfoundation.info/assests/img/logo.png" />
      </Head>

      <main className='container g-bg'>
        <Navbar/>
        <div style={{height:'calc(100vh - 46px)'}} className="w-full flex justify-center items-center">
         <a target="_blank" rel="noreferrer" href="https://rzp.io/l/sparkdonation">
         <button className="px-2 py-1 rounded border bg-gradient-to-tr from-[#ffcf9f] to-[#ff889c] text-xl hover:from-[ff88ic] hover:to-[#ffcf9f]">
            Donate
          </button>
         </a>
        </div>
      </main>

    </div>
  )
}
